services:
  rabbitmq:
    image: rabbitmq:4.0.9-alpine
    ports:
      - "35672:5672"
      - "45672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  push_api:
    build: .
    container_name: push_api
    command: pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  push_worker:
    build: .
    container_name: push_worker
    command: python app/consumer.py
    depends_on:
      - rabbitmq
